name: "Raju Prakruthi Vyavasaaya Kshethram"
title: "Raju Prakruthi Vyavasaaya Kshethram"
description: "Raju Prakruthi Vyavasaaya Kshethram | Heirloom Seeds | Desi Seeds | SPNF | Subash Palekar Natural Farming | ZBNF | Jinna Balu | Jinna Raju | Jinna Krishna "
meta_description: "Raju Prakruthi Vyavasaaya Kshethram | Heirloom Seeds | Desi Seeds | SPNF | Subash Palekar Natural Farming | ZBNF | Jinna Balu | Jinna Raju | Jinna Krishna "
logo: 'assets/img/farm_logo.png'
favicon: 'assets/img/farm_logo.png'
paginate: 12
baseurl: ''
url: ''
email: 'metuku@gmail.com'
locale: en_US
seo:
  keywords: 'Raju Prakruthi Vyavasaaya Kshethram'
  site_name: Raju Prakruthi Vyavasaaya Kshethram
og:
  type: "website"

plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap

sass:
  style: compressed
        
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
markdown: kramdown
highlighter: rouge
google-tag-manager-id: GTM-MTFQ8TF

social:
  name: Jinna Balu
  links:
    - https://twitter.com/FarmMethuku
    - https://www.facebook.com/methuku.farm/
    - https://www.instagram.com/methuku.farm/
    - https://farm.methuku.com/
## Verify ownership with several services at once using the following format
webmaster_verifications:
  google: XassWE0f9U0SuZSNHldIvE0dXEFQrezQjgaesx5HWlw
  bing: 1E642F36EC0479DC69135F989CDC274A
  yandex: 43039f2f4b41e2c3
  baidu: 1234
  facebook: 1234
  ahrefs: 51bddb95e8fc130687b6ef65736ca7afb4c52168083b13a5e11eb5f1f2a536d7

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
